// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBaVCFxSlxjXgFnXybKITb6u53piMrjjY',
    appId: '1:298753755267:web:55a7d349ee262a14c733b6',
    messagingSenderId: '298753755267',
    projectId: 'noteapp-e8e0d',
    authDomain: 'noteapp-e8e0d.firebaseapp.com',
    storageBucket: 'noteapp-e8e0d.appspot.com',
    measurementId: 'G-L9XE54VQPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZu9TLXD4yVvmsV5FVdTh7jjF43pvVRmM',
    appId: '1:298753755267:android:eaeaf00afa864a1ec733b6',
    messagingSenderId: '298753755267',
    projectId: 'noteapp-e8e0d',
    storageBucket: 'noteapp-e8e0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCylp0fbBz3Mpg3qEBcQYEJmnaRx1A-h90',
    appId: '1:298753755267:ios:f7caaadfc291ef13c733b6',
    messagingSenderId: '298753755267',
    projectId: 'noteapp-e8e0d',
    storageBucket: 'noteapp-e8e0d.appspot.com',
    androidClientId: '298753755267-56jivbejfqc4enphcb8r1cqt7rlr0qpc.apps.googleusercontent.com',
    iosClientId: '298753755267-8fqaahjd386ecgritji1kuo5fmnnqi3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCylp0fbBz3Mpg3qEBcQYEJmnaRx1A-h90',
    appId: '1:298753755267:ios:f7caaadfc291ef13c733b6',
    messagingSenderId: '298753755267',
    projectId: 'noteapp-e8e0d',
    storageBucket: 'noteapp-e8e0d.appspot.com',
    androidClientId: '298753755267-56jivbejfqc4enphcb8r1cqt7rlr0qpc.apps.googleusercontent.com',
    iosClientId: '298753755267-8fqaahjd386ecgritji1kuo5fmnnqi3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBaVCFxSlxjXgFnXybKITb6u53piMrjjY',
    appId: '1:298753755267:web:290b4e06745ab86bc733b6',
    messagingSenderId: '298753755267',
    projectId: 'noteapp-e8e0d',
    authDomain: 'noteapp-e8e0d.firebaseapp.com',
    storageBucket: 'noteapp-e8e0d.appspot.com',
    measurementId: 'G-SY0GNMD5CV',
  );
}
